penup()
backward(100)
for i in range(4):
    pensize(5)
    pendown()
    left(60)
    color("green")
    forward(50)
    right(120)
    color("blue")
    forward(50)
    color("red")
    right(120)
    forward(50)
    penup()
    left(180)
    forward(50)
color("green")